apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-catalog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-catalog
  template:
    metadata:
      labels:
        app: book-catalog
    spec:
      containers:
      - name: book-catalog-service
        image: sit722proj7.azurecr.io/book_catalog:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: DATABASE_URL
          value: "postgresql://sribook_user:wlop7IK1xI4SJVhGYamU2W3S5gGfpDKG@dpg-crva125ds78s73abc8cg-a.oregon-postgres.render.com/sribook"

---
apiVersion: v1
kind: Service
metadata:
  name: book-catalog
spec:
  selector:
    app: book-catalog
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
---    
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-management
  template:
    metadata:
      labels:
        app: inventory-management
    spec:
      containers: 
      - name: inventory-management-service
        image: sit722proj7.azurecr.io/inventory_management:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8081
        env:
        - name: PORT
          value: "8081"
        - name: DATABASE_URL
          value: "postgresql://sribook_user:wlop7IK1xI4SJVhGYamU2W3S5gGfpDKG@dpg-crva125ds78s73abc8cg-a.oregon-postgres.render.com/sribook"

---
apiVersion: v1
kind: Service
metadata:
  name: inventory-management
spec:
  selector:
    app: inventory-management
  type: LoadBalancer
  ports:
    - port: 8081
      targetPort: 8081
